# Generated by Django 4.2.7 on 2023-12-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='data_create',
            new_name='date_created',
        ),
    ]
